### PR TITLE
Alternative fix for Unity 5.6 that does not require the setZOrderOnTop fix.

### PR DESCRIPTION
**Pull request by nostek**
Creates a PopupWindow with 'layout' as child, instead of adding it to the activity.
This makes the Android version not require the setZOrderOnTop fix.

This is how Google Admob on Unity fixed it.
https://github.com/googleads/googleads-mobile-unity

Tested on Android 6.0.1

### CODE REVIEW

**Comment by KojiNakamaru** [comment]
Thank you very much. Unfortunately, the software keyboard seems not to be activated even if a text field is focused. Is it possible to solve this issue?

**Comment by nostek** [comment]
Ah, did not test for that.
I'll see if I can fix it when I'm back from holiday.

Apologies for not testing it thoroughly before making a pull request.

**Comment by antoniohof** [comment]
I just tested on the new Unity 2017 1.0 and the web view displays perfectly with the default unity android:name activity: com.unity3d.player.UnityPlayerActivity.

**Comment by KojiNakamaru** [comment]
@antoniohof Thanks for the information. Though I haven't tried yet, Unity 5.6.1p4 also seems to fix the issue (and thus it might be reflected in 2017 1.0):
https://unity3d.com/unity/qa/patch-releases?version=5.6
> (916119) - Android: Fixed a regression where Banner Ads are invisible, but still clickable.
I'll later add some note to README.md.

**Comment by nostek** [comment]
PopupWindow seems to not be working with keyboard input, so we can discard this.

**Comment by 2df** [comment]
I have a question, when I open a webView in game,then I touch "home" and return game back, will game be waked up with webview(if I leave android:name activity: com.unity3d.player.UnityPlayerActivity in unity 5.6.5)?

**Comment by KojiNakamaru** [comment]
The issue discussed here was only found in 5.6.0 and 5.6.1, so it should not affect 5.6.5. Therefore a web view should be shown up again when the game be waked up in the situation you describe.

**Comment by KojiNakamaru** [comment]
I've confirmed the sample app built by Unity 2017.4.11f1 with release build works without any issue.  You might install an incomplete apk as the first build for Android should have failed to adjust AndroidManifest.xml, as below:

image

**Comment by sky2005zx** [comment]
Thanks !! I Delete AndroidManifest and build again, and it work.

But there is another problem, my website has an autoplay html 5 video, it show in IOS, but in android, it is total black screen (But it show the play state)

How to fix it ? Thx

(Sorry for my poor English)

**Comment by KojiNakamaru** [comment]
Hmm, did you rebuild the app, as designated in the screenshot above? For video display,  https://github.com/gree/unity-webview/tree/4cc849f6920547dd1f7946cc81aa5143b89354eb#hardwareaccelerated is normally required.

**Comment by boboshu** [comment]
same when playing h5 video it is black screen on android . ios is ok.but when set hardwareaccelerated true. android is ok. I tested Uniwebview3 addons, when the hardwareaccelerated  is false android, it is not black screen. my unity version is unity2017.4.17f

**Pull request closed without merging**
