### PR TITLE
obsolete Warning

### PR DESCRIPTION
**Pull request by shinriyo**
IssuePluginEvent(eventID) is deprecated. Use IssuePluginEvent(callback, eventID) instead.

### CODE REVIEW

**Comment by KojiNakamaru** [comment]
Thank you for the pull request. The `webView` is however not a native function and cannot be passed as `callback`. This makes unity osx version crash. I'll later fix the warning separately.

**Comment by shinriyo** [comment]
Thank you for replying.
So, if you would like to hide warning, you sandwich there code by `#pragma warning disable 0618` and `#pragma warning restore 0618` C# preprocessor directives.

**Comment by KojiNakamaru** [comment]
Thanks for the comment. I've fixed the issue more completely, by supporting new `GL.IssuePluginEvent(callback, eventID)`:
cf. https://github.com/gree/unity-webview/commit/8d1a4d156d902994c49ce77c48ae02e7ee617f12

**Comment by shinriyo** [comment]
Thank you for fixing it.

**Pull request closed without merging**
